### ISSUE TITLE
What do i save he file as?

### ISSUE THREAD

**Issue by GalacticGaming0** [cankatx/discord-token-stealer#4]
so i wrote the code + the webhook in notepad++ what do i save the file as, i tried .exe it doesn't work

**Comment by CactusHamster** [comment]
It's a python file, not exe; if you want an exe file, you'll have to use Pyinstaller.
To use:
1. Install python (if you havent already, and install it to the PATH)
2. Save the code as a .py file
3. Run it with `python yourfile.py` to test
4. Send it to your victim
If you don't know how python works, I advise you learn some of the language before trying Pyinstaller.

**Comment by Sap196** [comment]
lol skid

**Comment by cankatx** [comment]
> 
> 
> lol skid

It's not I gave credit of who I used hes codes.

**Comment by CactusHamster** [comment]
Pretty sure he was talking about the issue's creator. Maybe we could close the issue?

**Comment by cankatx** [comment]
> Pretty sure he was talking about the issue's creator. Maybe we could close the issue? also.. uh... if you didn't actually improve the code, and just uploaded it, that makes you a script kiddie too 0~0

Oh okay also I added more browser supports and some bug fixes to the code that's why I created a new repo

**Comment by CactusHamster** [comment]
Perhaps forking and a pull request would be best for that?
